/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gilachus.chronometer3;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


public class Screen extends javax.swing.JFrame {
    Second second;
    Minute minute;
    Thousandth thousandth;
    Thread tMin, tSec, tTho;
    int lap;
    /**
     * Creates new form Screen
     */
    public Screen() {
        this.setTitle("Chronometer");
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        initComponents();
        minute = new Minute();
        tMin = new Thread(minute);
        second = new Second();
        tSec = new Thread(second);
        thousandth = new Thousandth();
        tTho = new Thread(thousandth);
        lap=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReset = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jTextMinute = new javax.swing.JTextField();
        jTextSecond = new javax.swing.JTextField();
        jTextThousandth = new javax.swing.JTextField();
        jButtonLap = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLaps = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jTextMinute.setText("0");
        jTextMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMinuteActionPerformed(evt);
            }
        });

        jTextSecond.setText("0");
        jTextSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSecondActionPerformed(evt);
            }
        });

        jTextThousandth.setText("0");
        jTextThousandth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextThousandthActionPerformed(evt);
            }
        });

        jButtonLap.setText("Lap");
        jButtonLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLapActionPerformed(evt);
            }
        });

        jTableLaps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableLaps);
        if (jTableLaps.getColumnModel().getColumnCount() > 0) {
            jTableLaps.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jTextSecond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextThousandth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextThousandth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonLap))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        try {
            minute.stop();
            Screen.jTextMinute.setText("0");
            second.stop();
            Screen.jTextSecond.setText("0");
            thousandth.stop();
            Screen.jTextThousandth.setText("0");
        } catch (Exception e){
                
        }   
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if(!tMin.isAlive()){
            tMin.start();
        }if(!tSec.isAlive()){
            tSec.start();
        }if(!tTho.isAlive()){
            tTho.start();
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jTextMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMinuteActionPerformed

    private void jTextSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSecondActionPerformed

    private void jButtonLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLapActionPerformed
        if(lap==0){
            Object[] col= new Object[3];
            col[0] = "lap";
            col[1] = "hour";
            col[2] = "total";
            Object[][] row = new Object[1][3];
            row[0][0] = "1";
            row[0][1] = jTextMinute.getText()+":"+
            jTextSecond.getText()+":"+
            jTextThousandth.getText();
            row[0][2] = jTextMinute.getText()+":"+
            jTextSecond.getText()+":"+
            jTextThousandth.getText();
            DefaultTableModel tm = new DefaultTableModel(row, col);
            jTableLaps.setModel(tm);    
            lap = 1;
        }else{
            DefaultTableModel tm = (DefaultTableModel)jTableLaps.getModel();
            Object[] row = new Object[3];
            row[0] = tm.getRowCount()+1;
            row[2] = jTextMinute.getText()+":"+
            jTextSecond.getText()+":"+
            jTextThousandth.getText();
            int min = Integer.parseInt(jTextMinute.getText());
            int sec = Integer.parseInt(jTextSecond.getText());
            int tho = Integer.parseInt(jTextThousandth.getText());
            Object total = jTableLaps.getModel().getValueAt(tm.getRowCount()-1, 2);
            String strTotal = (String)total;
            String[] timeVector = strTotal.split(":");
            int min2 = Integer.parseInt(timeVector[0]);
            int sec2 = Integer.parseInt(timeVector[1]);
            int tho2 = Integer.parseInt(timeVector[2]);
            int minRes = min - min2;
            int secRes = sec - sec2;
            int thoRes = tho - tho2;
            row[1] = Math.abs(minRes)+":"+
            Math.abs(secRes)+":"+
            Math.abs(thoRes);
            tm.addRow(row);
        }

    }//GEN-LAST:event_jButtonLapActionPerformed

    private void jTextThousandthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextThousandthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextThousandthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLap;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLaps;
    public static javax.swing.JTextField jTextMinute;
    public static javax.swing.JTextField jTextSecond;
    public static javax.swing.JTextField jTextThousandth;
    // End of variables declaration//GEN-END:variables
}
